# Generated by Django 3.2.4 on 2021-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210704_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Writer_name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
